---
- hosts: servers
  become: yes
  tasks:
    - name: print task1
      raw: echo hi-srikanth
      register: output1
    - name: print task2
      raw: echo hello-srikanth
      register: output2
    - debug: var=output1
    - debug: var=output2d
