---
- hosts: servers
  become: yes
  tasks:
   - name: install apache2
     apt: name=apache2 state=present
     when: ansible_os_family=="Debian"
   - name: start apache2
     service: name=apache2 state=started
